name: Run daily summary (KST 07:50)

on:
  schedule:
    - cron: "50 22 * * *"   # 22:50 UTC = 07:50 KST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install transformers sentencepiece requests beautifulsoup4 pytz

      - name: Inject secrets and run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python - <<'PY'
          import os, pathlib, subprocess, sys
          token = os.environ["TELEGRAM_TOKEN"]
          chat  = os.environ["CHAT_ID"]
          p = pathlib.Path("news_runner.py").read_text(encoding="utf-8")
          p = p.replace('TELEGRAM_TOKEN = "REPLACE_ME"', f'TELEGRAM_TOKEN = "{token}"')
          p = p.replace('CHAT_ID = "REPLACE_ME"', f'CHAT_ID = "{chat}"')
          pathlib.Path("news_runner_exec.py").write_text(p, encoding="utf-8")
          subprocess.check_call([sys.executable, "news_runner_exec.py"])
          PY
